config/routes.rb
Rails.application.routes.draw do
  get 'home/welcome'
  root to: "home#welcome"

  devise_for :users
  
  resources :memberships
  resources :students do
    collection {post :import}
  end
  resources :teachers do
    collection {post :import}
  end
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :membershipable, polymorphic: true
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:first_name, :last_name, :email, :phone, :membershipable_type, :membershipable_id)
    end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership, local: true) do |form| %>
  <% if membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :student_or_teacher %>
    <%= form.select :membershipable_type, ['Student', 'Teacher'] %>
  </div>

  <div class="field">
    <%= form.label :related_student %>
    <%= form.select :membershipable_id, Student.all.collect{|s| [s.full_name, s.id]} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<div class="uk-container">
<p id="notice"><%= notice %></p>

<div class="uk-card uk-card-default uk-card-body">
  <h3>Memberships</h3>

</div>

<table class="uk-table uk-table-striped uk-table-hover uk-table-middle">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.first_name %> <%= membership.last_name %></td>
        <td><%= membership.email %></td>
        <td><%= membership.phone %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Membership', new_membership_path %> -->
</div>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @membership.first_name %> <%= @membershp.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @membership.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @membership.phone %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>