config/routes.rb
Rails.application.routes.draw do
  get 'home/welcome'
  root to: "home#welcome"

  devise_for :users
  
  resources :memberships
  resources :students do
    collection {post :import}
  end
  resources :teachers do
    collection {post :import}
  end
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :teacher
  has_many :memberships, as: :membershipable

  require 'csv'

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      student_details = row.to_hash.merge!(teacher_id: Teacher.find_by(section_id: row['homeroom']).id)
      Student.create!(student_details)
    end
  end

  def self.search(search)
    where("first_name ILIKE ? OR last_name ILIKE ?", "%#{search}%", "%#{search}%")
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
    if params[:search]
      @students = Student.search(params[:search]).order("last_name ASC")
    else
      @students = Student.all.order("last_name ASC")
    end
  end

  def import
    Student.import(params[:file])
    redirect_to root_url, notice: "Student Data Imported"
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :middle_name, :student_id, :homeroom)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :homeroom %>
    <%= form.text_field :homeroom %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<div class="uk-container">
  <p id="notice"><%= notice %></p>
  <ul uk-accordion>
    <li>
      <a class="uk-accordion-title" href="#">Upload More Students</a>
      <div class="uk-accordion-content">
        <h4>Import Student Data</h4>
        <%= form_tag import_students_path, multipart: true do %>
          <%= file_field_tag :file %>
          <%= submit_tag "Import CSV" %>
        <% end %>
      </div>
    </li>
    <li>
      <a class="uk-accordion-title" href="#">Create a New Student</a>
      <div class="uk-accordion-content">
        <%= link_to 'New Student', new_student_path %>
      </div>
    </li>
  </ul>

  <div class="uk-card uk-card-default uk-card-body">
    <h3>Students</h3>

    <div class="uk-grid-small" uk-grid>
      <%= form_tag(students_path, :method => "get", id: "search-form", class: "uk-search uk-search-default uk-flex uk-width-1-1") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Students", class: "uk-search-input" %>
        <%= submit_tag "Search", :name => nil, class: "uk-button uk-button-primary uk-margin-left uk-flex-right" %>
      <% end %>
    </div>

    <% if @students.blank? %>
      <div class="uk-alert">
        <h4>There are no students by the name of <%= params[:search] %>.</h4>
      </div>
    <% end %>
  </div>

  <table class="uk-table uk-table-striped uk-table-hover uk-table-middle">
    <thead>
      <tr>
        <th>First name</th>
        <th>Middle name</th>
        <th>Last name</th>
        <th>Student</th>
        <th>Teacher</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><%= student.first_name %></td>
          <td><%= student.middle_name %></td>
          <td><%= student.last_name %></td>
          <td><%= student.student_id %></td>
          <td><%= student.teacher.name %></td>
          <td><%= link_to 'View Class', teacher_path(student.teacher.id), class: "uk-button uk-button-default" %></td>
          <td><%= link_to 'View Student', student, class: "uk-button uk-button-default" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<div class="uk-container">
  <p id="notice"><%= notice %></p>

  <div class="uk-margin-bottom">
    <%= link_to 'View Class', teacher_path(@student.teacher) %> |
    <%= link_to 'Edit Student', edit_student_path(@student) %>
  </div>

  <div class="uk-card uk-card-primary uk-card-body">
    <h3 class="uk-card-title"><%= @student.first_name %> <%= @student.middle_name %> <%= @student.last_name %> - <%= @student.student_id %></h3>
    <h3 class="uk-card-title uk-position-right uk-margin-right"><%= @student.teacher.name%></h3>
  </div>

  
  <table class="uk-table uk-table-striped uk-table-hover uk-table-middle">
    <thead>
      <tr>
        <th>Member Name</th>
        <th>Member Email</th>
        <th>Member Phone</th>
      </tr>
    </thead>
    <tbody>
      <% @student.memberships.each do |member| %>
        <tr>
          <td><p><%= member.first_name.capitalize %> <%= member.last_name.capitalize %></p></td>
          <td><p><%= member.email %></p></td>
          <td><p><%= member.phone %></p></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>