config/routes.rb
Rails.application.routes.draw do
  get 'home/welcome'
  root to: "home#welcome"

  devise_for :users
  
  resources :memberships
  resources :students do
    collection {post :import}
  end
  resources :teachers do
    collection {post :import}
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :students
  has_many :memberships, as: :membershipable
  require 'csv'

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Teacher.create! row.to_hash
    end
  end

  def self.search(search)
    where("name ILIKE ? OR grade ILIKE ?", "%#{search}%", "%#{search}%")
  end

  def class_memberships
    Student.joins(:memberships).where(teacher_id: self.id).map(&:memberships)
  end

  def membership_percentage
    (class_memberships.count.to_f / self.students.count.to_f) * 100
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
    if params[:search]
      @teachers = Teacher.search(params[:search]).order("name ASC")
    else
      @teachers = Teacher.all.order("name ASC")
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  def import
    Teacher.import(params[:file])
    redirect_to teachers_url, notice: "Teacher Data Imported"
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :grade, :section_id, :room, :class_type)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.text_field :section_id %>
  </div>

  <div class="field">
    <%= form.label :room %>
    <%= form.text_field :room %>
  </div>

  <div class="field">
    <%= form.label :class_type %>
    <%= form.text_field :class_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<div class="uk-container">

  <p id="notice"><%= notice %></p>
  <div class="uk-card uk-card-default uk-card-body">
    <h3>Teachers</h3>
    <div class="uk-grid-small" uk-grid>
      <%= form_tag(teachers_path, :method => "get", id: "search-form", class: "uk-search uk-search-default uk-flex uk-width-1-1") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Teachers by name or grade", class: "uk-search-input" %>
        <%= submit_tag "Search", :name => nil, class: "uk-button uk-button-primary uk-margin-left uk-flex-right" %>
      <% end %>
    </div>

    <% if @teachers.blank? %>
      <div class="uk-alert">
        <h4>There are no teachers by the name of <%= params[:search] %>.</h4>
      </div>
    <% end %>
  </div>

  <table class="uk-table uk-table-striped uk-table-hover uk-table-middle">
    <thead>
      <tr>
        <th>Name</th>
        <th>Grade</th>
        <th>Section</th>
        <th>Room</th>
        <th>Class type</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @teachers.each do |teacher| %>
        <tr>
          <td><%= teacher.name %></td>
          <td><%= teacher.grade %></td>
          <td><%= teacher.section_id %></td>
          <td><%= teacher.room %></td>
          <td><%= teacher.class_type %></td>
          <td><%= link_to 'View Class', teacher, class: "uk-button uk-button-default" %></td>
          <!-- <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
          <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>

  <div>
    <h4>Import Teacher Data</h4>
    <%= form_tag import_teachers_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Import CSV" %>
    <% end %>
  </div>

  <br>

  <%= link_to 'New Teacher', new_teacher_path %>
</div>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<div>
  <div class="uk-card uk-card-primary uk-card-body">
    <div class="uk-grid-divider uk-child-width-expand@s" uk-grid>
      <div>
        <h3 class="uk-card-title"><%= @teacher.name %> - Grade <%= @teacher.grade %></h3>
        <%= link_to 'Edit Teacher Info.', edit_teacher_path(@teacher) %> |
        <%= link_to 'Back', teachers_path %>
      </div>
      <div>
        <p>
          <strong>Section:</strong>
          <%= @teacher.section_id %>
        </p>

        <p>
          <strong>Room:</strong>
          <%= @teacher.room %>
        </p>

        <p>
          <strong>Class type:</strong>
          <%= @teacher.class_type %>
        </p>
      </div>
      <div><h1 class="uk-position-center"><%= @teacher.membership_percentage.to_i %>% Membership</h1></div>
    </div>
  </div>
</div>

<div class="uk-margin-top uk-container">
  <button class="uk-button uk-button-default uk-margin-small-right" type="button" uk-toggle="target: #membership-modal"><span uk-icon="user"></span> Add Membership</button>

  <!-- This is the modal -->
  <div id="membership-modal" uk-modal>
    <div class="uk-modal-dialog uk-modal-body">
      <h2 class="uk-modal-title">Create New PTA Membershp</h2>
      <form class="uk-form-stacked">
        <div class="uk-margin">
          <label class="uk-form-label" for="form-stacked-text">First Name</label>
          <div class="uk-form-controls">
            <input class="uk-input" id="form-stacked-text" type="text" placeholder="First Name">
          </div>
        </div>
        <div class="uk-margin">
          <label class="uk-form-label" for="form-stacked-text">Last Name</label>
          <div class="uk-form-controls">
            <input class="uk-input" id="form-stacked-text" type="text" placeholder="Last Name">
          </div>
        </div>
        <div class="uk-margin">
          <label class="uk-form-label" for="form-stacked-text">Email</label>
          <div class="uk-form-controls">
            <input class="uk-input" id="form-stacked-text" type="text" placeholder="Email Address">
          </div>
        </div>
        <div class="uk-margin">
          <label class="uk-form-label" for="form-stacked-text">Phone</label>
          <div class="uk-form-controls">
            <input class="uk-input" id="form-stacked-text" type="text" placeholder="Phone Number">
          </div>
        </div>
        <div class="uk-margin">
          <label class="uk-form-label" for="form-stacked-select">Select Membership Type</label>
          <div class="uk-form-controls">
            <select class="uk-select" id="form-stacked-select">
            <option>Student</option>
            <option>Teacher</option>
            </select>
          </div>
        </div>
        <div class="uk-margin">
          <label class="uk-form-label" for="form-stacked-select">Select Related</label>
          <div class="uk-form-controls">
            <select class="uk-select" id="form-stacked-select">
            <option>Student Name</option>
            <option>Other Student</option>
            </select>
          </div>
        </div>
      </form>
      <p class="uk-text-right">
          <button class="uk-button uk-button-default uk-modal-close" type="button">Cancel</button>
          <button class="uk-button uk-button-primary" type="button">Save</button>
      </p>
    </div>
  </div>
</div>

<div class="uk-container">
  <p id="notice"><%= notice %></p>
  <div>
    <h3>Class Roster</h3>
      <div>
        <table class="uk-table uk-table-divider uk-table-hover uk-table-middle">
          <thead>
            <tr>
              <th class="uk-table-shrink">Memberships</th>
              <th>Name</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @teacher.students.each do |student| %>
              <tr>
                <td>
                  <% if student.memberships.any? %>
                    <span class="uk-margin-small-right" uk-icon="check"></span>
                  <% else %>
                    <span></span>
                  <% end %>
                </td>
                <td>
                  <%= student.first_name %>
                  <%= student.middle_name %>
                  <%= student.last_name %>
                </td>
                <td><%= link_to 'View Student', student, class: "uk-button uk-button-default"%></td>
            <% end %>
            </tr>
          </tbody>
      </div>
  </div>
</div>